apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: django-messaging-app
        version: blue
    spec:
      containers:
      - name: django-messaging-app
        image: django-messaging-app:v2.0 # Using a versioned image
        imagePullPolicy: Never
        ports:
        - containerPort: 8000